# Site settings
title: Jiupeng Zhang
SEOTitle: Jiupeng Zhang's Blog
header-img: https://github.com/jiup/jiup.github.io/raw/master/img/home-bg.jpg
email: jiupeng.zhang@gmail.com
description: "Developing, Travelling, Exploring"
keyword: "Jiupeng Zhang, Zapler, @Zapler, Jiupeng Zhang's Blog, Zapler's Blog, 张九鹏, 张九鹏的博客, 博客, 个人网站"
url: "https://blog.jiupeng.me"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
#weibo_username:     
#zhihu_username:     
github_username:    ZhangJiupeng
instagram_username:    2ap1er
#twitter_username:
#facebook_username:  
# linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["portfolio","about.html","contact.html","resume"]
anchorjs: false                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highligher: rouge
  syntax_highlighter_opts:
      # Rouge Options › https://github.com/jneen/rouge#full-options
      css_class: 'highlight'
      #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
      span:
        line_numbers: false
      block:
        line_numbers: true
        start_line: 1



# Disqus settings
disqus_username: Zapler

# Netease setttings
#netease_comment: false


# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-79365960-3'            # Format: UA-xxxxxx-xx
#ga_domain: blog.jiupeng.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Where there’s a will, <br/>there’s a way..."
sidebar-avatar: /img/avatar-zapler.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
#friends: [
    #{
    #     title: "Su",
    #     href: "http://su.gallery/"
    # }
#]
